### PR TITLE
Fix some warnings

### PR DESCRIPTION
**Pull request by hannobraun**
This fixes some warnings I noticed while working with the project. See commits for details.

### CODE REVIEW

**Review by arendjr — APPROVED** [review]
Thanks so much!

**Comment by arendjr** [comment]
Oh, I do see some of the `expected_*` files need to be updated for the tests to pass.

**Comment by hannobraun** [comment]
I've added a commit that fixes the test failures. While doing that, I noticed that the doc comments this pull request updates are also used to generate doc comments in TypeScript code. I don't know, if the `<url>` syntax that `cargo doc` recognizes is valid syntax there.

I also rebased the whole branch, as it was out of date with `main`.

**Comment by arendjr** [comment]
> I don't know, if the `<url>` syntax that `cargo doc` recognizes is valid syntax there.

Yeah, that's a fair point. But I'd happily accept that as so-be-it for now :)

Thanks again!

**Pull request merged**
