### PR TITLE
Fix 'Singlepass' import for Runtime bindings. 

### PR DESCRIPTION
**Pull request by AmeanAsad**
Opening this to tackle this issue: https://github.com/fiberplane/fp-bindgen/issues/161

### Changes:
- Just updated the import of `Singlepass` from wasmer.

### CODE REVIEW

**Comment by arendjr** [comment]
Looks like a good solution, thanks! I just triggered the tests, but I suspect the formatting will need to be fixed so it's consistent between the generator and the expected bindings.

**Comment by AmeanAsad** [comment]
Seems like the tests are failing due to some issue with the deno runtime. I have not used deno before, is this is something from my end that I should fix? 

Screen Shot 2023-01-03 at 1 42 26 PM

**Comment by arendjr** [comment]
Yeah, that was just a temporary hick-up on the mirror (I guess we should set up the CI caching for Deno). I reran them, and it seems to now only be down to the formatting issue :)

**Comment by arendjr** [comment]
Thanks so much!

**Review by arendjr — APPROVED** [review]

**Pull request merged**
