### PR TITLE
#104 generate README from lib.rs

### LINKED ISSUE #104: Improve docs.rs
Currently, the documentation on docs.rs is pretty poor, we should at least include the current readme.

### PR DESCRIPTION
**Pull request by joepio**
closes #104 

- Uses `cargo-rdme` to generate README.md from `fp-bindgen/src/lib.rs`
- Moved readme to `lib.rs` so it is shown on docs.rs / crates.io
- Updates contribute guide
- Removes duplicate README file

Point of possible improvement: `test.yml` could check if the README is up to date, if you add something like this:

```yml
      - name: Check if readme isn't out of date
        run: cargo install cargo-rdme && cargo-rdme --check
```

But that's not in this PR.

### CODE REVIEW

**Review by arendjr — APPROVED** [review]
This is really neat, thanks a ton!

I wonder why the tests didn't trigger though. Could be because it's a branch from your own fork? :thinking:

**Comment by joepio** [comment]
@arendjr 

Yeah github is [a bit strict](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks) about running external PRs by default to prevent misuse / high cost. You can [adjust this setting per repo](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#configuring-required-approval-for-workflows-from-public-forks), though.

**Comment by arendjr** [comment]
Ah, I see. Then my PR might not have the desired result yet :) I cannot currently access those settings as we set up our repositories through Terraform... but I'm on it!

**Comment by joepio** [comment]
I've fixed the imports, but the code wouldn't run still. Basically, the macro's all throw errors in the testing context:

```
error[E0425]: cannot find function `__fp_declare_import_fns` in this scope
 --> src/lib.rs:161:1
  |
6 | / fp_bindgen::prelude::fp_bindgen!(fp_bindgen::BindingConfig {
7 | |     bindings_type,
8 | |     path: &format!("bindings/{}", bindings_type)
9 | | });
  | |__^ not found in this scope
```

So I've added `ignore` to the code blocks, for now. I think making all code examples executable / testable is a good next step.

Maybe we'll need a `build.rs` script + re-use of example protocol to fix this.

**Pull request merged**
